// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJiMYYDQsXQBwxtG5nLOGM8nhzpF6dEJA',
    appId: '1:936381910842:web:62f0090e8f75f71f1dca03',
    messagingSenderId: '936381910842',
    projectId: 'museafi-c8f99',
    authDomain: 'museafi-c8f99.firebaseapp.com',
    storageBucket: 'museafi-c8f99.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwhdfgSHli4PZyfjkhnER6lzeD85inLAg',
    appId: '1:936381910842:android:88d71cbf99ebf3501dca03',
    messagingSenderId: '936381910842',
    projectId: 'museafi-c8f99',
    storageBucket: 'museafi-c8f99.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHU4-4JWIF_VWx1yOj4vZqdLwQIZrj7iM',
    appId: '1:936381910842:ios:cc11b295a76b6c491dca03',
    messagingSenderId: '936381910842',
    projectId: 'museafi-c8f99',
    storageBucket: 'museafi-c8f99.appspot.com',
    iosBundleId: 'com.example.musefi',
  );
}
